format = '$os$time$directory$all'

[username]
disabled = true

[hostname]
disabled = true

[os]
disabled = false
format = '[$symbol]($style) '
style = "cyan"

[os.symbols]
Ubuntu = 'U'
Windows = 'W'
Debian = 'D'

[time]
style = 'gray'
format = '\[[$time]($style)\] '
disabled = false

[directory]
truncation_length = 10
truncate_to_repo = false

[character]
success_symbol = 'üçä'
error_symbol = 'üçâ'

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
